name:                haskellbook
version:             0.1.0.0
github:              "michaelwebb76/haskellbook"
license:             BSD3
author:              "Michael Webb"
maintainer:          "michaelwebb76@gmail.com"
copyright:           "2020 Michael Webb"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaelwebb76/haskellbook#readme>

dependencies:
- base >= 4.7 && < 5
- checkers
- containers
- hspec
- protolude
- QuickCheck
- time

library:
  source-dirs: .

executables:
  haskellbook:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbook

tests:
  haskellbook-test:
    main:                Spec.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellbook
